# ADMIN
{
	collections(first: 250, query: "template_suffix:'author'") {
        edges {
            node {
                id
                title
                handle
                updatedAt
                sortOrder
                templateSuffix
                metafields(first: 5) {
                    edges {
                        node {
                            key
                            value
                        }
                    }
                }
            }
        }
        pageInfo {
            hasPreviousPage
            hasNextPage
            startCursor
            endCursor
        }
	}
}

# STOREFRONT -- https://shopify.dev/docs/api/storefront
query ($cursor: String) {
    collections(first: 2, query:"title:author*", after: $cursor) {
          edges {
              node {
                  id
                  title
                  handle
                  updatedAt
                  image {
                    url
                  }
                  authorLastFirst: metafield(namespace: "godine", key: "author_last_first") {
                      value
                      type
                  }
              }
          }
          pageInfo {
              hasPreviousPage
              hasNextPage
              startCursor
              endCursor
          }
    }
}